Cargo.toml, LICENSE, examples/datatypes.rs, examples/object.rs, examples/registration.rs, examples/simple.rs, src/crypto.rs, src/database.rs, src/interface.rs, src/interface/traits.rs, src/interfaces.rs, src/lib.rs, src/pairing.rs, src/registration.rs, src/types.rs
It was already under Apache 2.0, but license notice was missing.
=> Add Apache 2.0 License

Cargo.toml
This is useful for cargo-bitbake tool
Relate-to: https://github.com/astarte-platform/astarte-device-sdk-rust/pull/16
Bug: https://github.com/astarte-platform/astarte-device-sdk-rust/issues/20
Signed-off-by: Philippe Coval <philippe.coval@huawei.com>
=> build: Use SPDX Licence format

src/database.rs, src/lib.rs, src/types.rs
The previous implementation was inconsistent and broke deserialization
=> Refactor and fix deserialization for unset

Cargo.toml, src/types.rs
We have to specialize the `from_bson_array` macro for `DateTimeArray` because bson has its own datetime type that doesn't support `FromIterator`
=> Update bson dependency

src/database.rs, src/interfaces.rs, src/lib.rs
Do not clear the properties database after sending an  `emptyCache` message. This is a bug which may lead to device information loss. Instead, send all device-owned properties, as in e.g. the [Java](https://github.com/astarte-platform/astarte-device-sdk-java/blob/3de54b55d6074d62e468c2cef7030f791426fae3/DeviceSDK/src/main/java/org/astarteplatform/devicesdk/transport/mqtt/AstarteMqttV1Transport.java#L466-L474) or [Go](https://github.com/astarte-platform/astarte-device-sdk-go/blob/bf45b7921f32edf371a85f5be5a2bfcf3d6b515c/device/protocol_mqtt_v1.go#L187-L233) SDKs. 
In order to clean (parts) of the properties database, handling of purge properties messages should be implemented, as stated in the [Astarte doc](https://docs.astarte-platform.org/latest/080-mqtt-v1-protocol.html#purge-properties) …
=> Protocol: fix behavior after device `emptyCache` message

examples/object.rs, src/interfaces.rs
Make validation fail when a trailing /  is present in the path of an object interface, reverting the previous behavior
=>  Disallow trailing / on object path

.github/workflows/build-workflow.yaml
Due to instability, replace nightly with beta for the CI
=> Replace nightly with beta for the CI

src/e2etest/e2etest.rs
Trailing / in object path was causing widespread problems for the e2e test, fix everything to work without it
Related: #41
=> E2E test: remove forbidden trailing / in endpoint

examples/database.rs, examples/deviceproperties.rs, examples/object.rs, examples/simple.rs
It is not optimal to use std::thread in async
=> Remove thread::sleep from async code

.github/workflows/e2e-test.yaml
Don't fail when a random device id starts with '-'
=> Fix astartectl command line for e2e test

src/interface.rs, src/interfaces.rs, src/lib.rs, src/types.rs
In the case of a server-owned longinteger mapping, Astarte sends an integer number if the value is small enough.
This behavior was not taken into account during the data validation. 
A condition was add in the `eq` function that compares the type of the data received with the mapping type.
Added some tests.
=> Fix handling of int32 payload on LongInteger mapping

src/interface.rs, src/lib.rs
Add the capability to dynamically manipulate the introspection adding an interface after the device connection.
=> Add Interface after device connection

src/e2etest/e2etest.rs, src/interfaces.rs, src/lib.rs
The unset function definition makes use of an unused generic type definition.
During tests, a bug on validation that prevents the unset functionality emerged.
This commit fixes both issues.
Close #77 
=> Remove generic type from unset function signature

src/interface.rs, src/lib.rs
Add the capability to remove an interface from introspection after device connection.
=> Add dynamic interface remove

src/interface.rs, src/lib.rs
Replaced `0` magic number in `store_property_on_send` with the actual `version_major` meant to be there.
=> Fix the magic number in `store_property_on_send`

src/lib.rs
During development `AstarteSdk::send_object` gave me a an `AstarteError`, when I printed it (using the Display trait) all it said was `send error`
After this change it shows the actual inner error: `end error (Interface does not exists)`
=> Display actual error message in AstarteError

.github/workflows/build-workflow.yaml, Cargo.toml
Perform all the operations in the `build-workflow` also for the `v1.59.0` of Rust.
Do not run anything for `beta` versions of Rust.
Roll back `env_logger` to latest version supported by Rust `v1.59.0`
Closes #91
=> Locking CI to v1.59.0

src/e2etest/e2etest.rs, src/interfaces.rs, src/lib.rs, src/types.rs
All the warnings were generated by the deprecated function `timestamp`. They have been solved by replacing it with `timestamp_opt`.
Closes #97
=> Resolve warnings from tests

src/lib.rs, src/types.rs
Implement the `TryFrom` trait for the base types from an `AstarteType`.
Closes #88.
=> Conversion from astarte type

Cargo.toml, examples/database.rs, examples/deviceproperties.rs, examples/object.rs, examples/registration.rs, examples/simple.rs, src/builder.rs, src/database.rs, src/e2etest/e2etest.rs, src/interfaces.rs, src/lib.rs, src/types.rs
Rename package from `astarte_sdk` to `astarte-device-sdk` (automatically translated to `astarte_device_sdk` inside the code) to better adhere to common RUST naming conventions.
Rename various APIs for better understandability.
Close #57 
=> API cleanup

src/interfaces.rs, src/types.rs
The conversion from AstarteType Double or LongInteger supports also Integer, so the end user will be able to use the try_into trait, without having to match Integer/Double in separately block.
Add tests on the comparison between MappingType e AstarteType.
Close #114 .
=> Handle the reception of an Integer value in a Mapping with type Double

.github/workflows/build-workflow.yaml, .gitignore, Cargo.toml, astarte-device-sdk-derive/Cargo.toml, astarte-device-sdk-derive/src/lib.rs, examples/object.rs, src/e2etest/e2etest.rs, src/interfaces.rs, src/lib.rs, src/types.rs
This PR introduces the procedural macro and trait `AstarteAggregate`.
Using this macro with the `derive` function over a compatible struct makes it possible to send it as an aggregate.
Closes #112. Closes #111.
=> Implement AstarteAggregate trait and macro

src/lib.rs
Change signature of send function to accept try_into trait.
The use of try_into trait allows to send the base type f64/f32 that support only the try_into trait.
Close #117
=> Change signature of  send function

.github/workflows/build-workflow.yaml, Cargo.toml, src/lib.rs
This PR proposes an alternative import structure for  `AstarteAggregate`.
Previously a user of the SDK wanting to use `#[derive(AstarteAggregate)]` would have needed to add as separate dependencies: `astarte-device-sdk` and `astarte-device-sdk-derive`.
And then in the sources add the following double `use`:
```
use astarte_device_sdk::AstarteAggregate;
use astarte_device_sdk_derive::AstarteAggregate;
```
With the changes inculded in this PR a user only needs to specify the feature `astarte-device-sdk-derive` for the crate `astarte-device-sdk` in its `Cargo.toml` file. Avoiding the double dependency.
In addition in the source files only a single `use` is required:
```
use astarte_device_sdk::AstarteAggregate;
```
=> Add AstarteAggregate as a crate feature.

examples/database.rs, examples/deviceproperties.rs, examples/object.rs, examples/registration.rs, examples/simple.rs, src/e2etest/e2etest.rs, src/interface.rs, src/interfaces.rs, src/lib.rs, src/pairing.rs, src/types.rs
Rust version [v1.67](https://blog.rust-lang.org/2023/01/26/Rust-1.67.0.html) brings some new/improved linting rules in `clippy`.
This PR fixes complaints from `clippy` for this Rust version.
=> Fix for Rust version v1.67

examples/database.rs, examples/deviceproperties.rs, examples/object.rs, examples/simple.rs, src/database.rs, src/interfaces.rs, src/lib.rs, src/options.rs, src/pairing.rs, tests/e2etest/main.rs
AstarteOptions does not follow the builder pattern, and a `build()` method that only clones the original object is superflous. Change the name and methods to better reflect the actual behavior of the AstarteOptions struct.
=> Remove AstarteOptions build method

src/lib.rs
Rename BuilderError to OptionsError to reflect the change in terminology
=> Rename BuilderError to OptionsError

README.md, src/database.rs, src/interface.rs, src/lib.rs, src/options.rs, src/registration.rs, src/types.rs
Adds docstrings to all the methods and data structures visible outside the crate.
Two other changes come bundled in this PR:
- Some of the methods of the `Interface` enumerator have been made public only inside of the crate. 
- The `handle_events()` has been splitted in two. This eases readability and prevents eccessive indentation.
Preparation for #70.
Closes #129.
=> Improved docstrings

README.md, src/lib.rs
Change to `rust` syntax highlighting.
In order to pass the validation of the example provided with the Readme, a full example was provided.
=> README: Fix syntax highlighting

astarte-device-sdk-derive/Cargo.lock, examples/object.rs, src/interface/mod.rs, src/interfaces.rs, src/lib.rs, src/options.rs, src/pairing.rs, src/registration.rs, src/types.rs, tests/e2etest/mock_data_aggregate.rs
Make the types and functions pub only when they are returned or used outside the crate.
Closes #165
=> refactor(interface): clean up and clarify the visibility of types

.github/workflows/e2e-test.yaml, tests/e2etest/main.rs
Some fixes for the end to end tests:
- Handle correctly a failure of `POST` or `DELETE` HTTPS requests.
- Bump up version of Astarte in CI to `1.0.4`
- Removes the not necessary `ignore_ssl_errors` flag in the device initialization.
Closes #142
=> e2e tests: bump up version of Astarte Cluster action and fix a related issue.

.github/dependabot.yml, .github/workflows/build-workflow.yaml, .github/workflows/e2e-test.yaml, .github/workflows/reuse-lint.yaml, .github/workflows/test.yaml, Cargo.lock, Cargo.toml, README.md, examples/object_datastream/main.rs, src/database.rs, src/lib.rs
Add the ci workflow to test on windows-latest. Use vcpkg to install openssl and set VCPKG_ROOT to the vcpkg installation path. This takes the rust-openssl ci.yml as example.
Closes #37
=> ci(test): add ci workflow to test on windows

Cargo.lock, Cargo.toml, src/crypto.rs, src/lib.rs, src/options.rs, src/pairing.rs
Make all the dependencies use rustls for TLS, still using openssl to generate the keys. Remove unused features from tokio to slim down the crate.
Closes #191
=> refactor(deps): update dependencies and clean up features

.github/workflows/test.yaml, Cargo.lock, Cargo.toml, examples/individual_properties/interfaces/org.astarte-platform.rust.examples.individual-properties.DeviceProperties.json, src/lib.rs, src/mock.rs
Mock the AsyncClient and EventLoop of the SDK, so we can unit test the
SDK without having to connect to a broker.
Closes #180
=>  test(mock): introduce mocking for the AstarteSDK

.github/workflows/test.yaml
Use the Github Actions Cache as a vcpkg binary cache.
=> feat(ci): use vcpkg binary cache

.github/workflows/e2e-test.yaml, .github/workflows/test.yaml, tests/e2etest/main.rs
Add an environment variable for the pairing URL, and make the API URL variable include the appengine path.
=> ci(e2e): make the e2e test runnable locally

CHANGELOG.md, README.md, examples/individual_datastream/main.rs, examples/individual_properties/main.rs, examples/object_datastream/main.rs, src/lib.rs, tests/e2etest/main.rs
This prevents some clones while creating the AstarteSdk object. Since
the AstarteOptions can be cloned outside of the new function, or usually
the entire SDK object is cloned. This also removes the mqtt_options from
the SDK, because it's never used and it's a fair large object (circa
300 bytes).
=>  refactor(options): require ownership of the options 

CHANGELOG.md, README.md, astarte-device-sdk-derive/src/lib.rs, examples/individual_datastream/main.rs, examples/individual_properties/main.rs, examples/object_datastream/main.rs, src/crypto.rs, src/database.rs, src/error.rs, src/interface/def.rs, src/interface/error.rs, src/interface/mapping/endpoint.rs, src/interface/mapping/mod.rs, src/interface/mapping/path.rs, src/interface/mod.rs, src/interface/validation.rs, src/interfaces.rs, src/lib.rs, src/options.rs, src/pairing.rs, src/topic.rs, src/types.rs
- Rename the main error `Error`
- Make the other errors names more clear
- Make all errors non-exhaustive
=> refactor(error): rename error, make them non exaustive and give them specific names

Cargo.lock, Cargo.toml, src/database.rs, src/error.rs, src/interfaces.rs, src/lib.rs, src/payload.rs, src/properties.rs, src/types.rs
Use Serialize and Deserialize to not allocate an additional HashMap when working with the payload. Separate the types errors int the specific module. Check the length of the control payload after deflating it and remove the unwraps.
=> feat(serialize/payload): improve ser/de and control payload

src/database.rs, src/error.rs, src/interface/error.rs, src/interface/mod.rs, src/interfaces.rs, src/lib.rs, src/properties.rs
The database trait now requires an AstarteType ref. The instructions in the event handler have been reordered to avoid cloning the payload when not needed. This also improves the deserialization which is done only once. Cleaned up some functions that are unused.
=>  refactor(interfaces): return and pass references when possible 

CHANGELOG.md, src/types.rs
When deserializing an empty bson array, we whould access the first element to know the type. This is not possible when the array is empty, and it would panic.
=>  fix(type): panic when deserializing empty bson array 

CHANGELOG.md, Cargo.lock, Cargo.toml, astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-derive/Cargo.lock, astarte-device-sdk-derive/Cargo.toml, src/error.rs, src/store/error.rs
- Fix documentation building.
Specify a version on `astarte-device-sdk-derive` because all dependencies must have a version specified when publishing.
Note: The published dependency will use the version from crates.io, the `path` specification will be removed from the dependency declaration.
=> Prepare release v0.6.0

CHANGELOG.md, src/lib.rs, src/payload.rs, src/store/sqlite.rs
This is the documented way on how to unset a property. Before we were sending a bson document with a null value which was also working, but it's not the way described in the mqtt-v1-protocol.
=> fix(unset): send an empty buffer on property unset

.github/workflows/test.yaml
With the migration to `clap` v4 by tarpaulin there is an undocumented breaking change on the coverage output since now the ValueEnum default to kebab case.
=> fix(tarpaulin): fix casing of the out option Xml -> xml

src/store/error.rs, src/store/mod.rs
This will let the error be passed to a tokio task. The error is overzealous on the Sync bound, but most of the methods of the Error trait requires it anyway so I think it's safe to add.
=> fix(store): add correct Send + Sync + 'static for tokio

.github/workflows/check.yaml, Cargo.toml
Make the patch/minor version of the dependencies match the actual required one this will loosen the requirements of the library. Add a ci action to check that the direct-minimal-versions is respected.
=> refactor(deps): loosen the dependencies minimum version reqs

CHANGELOG.md, Cargo.lock, Cargo.toml, migrations/20230622092054_init.sql, queries/load_all_props.sql, queries/load_prop.sql, queries/store_prop.sql, sqlx-data.json, src/error.rs, src/interface/def.rs, src/interface/error.rs, src/interface/mapping/endpoint.rs, src/interface/mapping/iter.rs, src/interface/mapping/mod.rs, src/interface/mapping/path.rs, src/interface/mapping/vec.rs, src/interface/mod.rs, src/interfaces.rs, src/lib.rs, src/payload.rs, src/store/mod.rs, src/store/sqlite.rs, src/topic.rs, src/types.rs, src/validate.rs, tests/e2etest/main.rs
Fixes a bug when deserializing integer arrays of mixed sizes received from astarte. Also improve the validation when sending and receiving data, introduced more ergonomic ways to access the interfaces mappings/objects. Upgraded to hard errors when interfaces are non-existing or of a different type.
Closes #238
=> fix(serde): serialize and deserialize mixed arrays

CHANGELOG.md, src/interface/def.rs, src/interface/mapping/iter.rs, src/interface/mapping/mod.rs, src/interface/mod.rs, src/interfaces.rs
Make the interface doc and description deserializable when there are escaped characters in the string.
Closes #250
=> fix(interface): make escaped strings deserializable

CHANGELOG.md, astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-derive/src/lib.rs, src/event.rs, src/interface/mapping/endpoint.rs, src/interface/mapping/mod.rs, src/interface/mapping/path.rs, src/interface/mod.rs, src/lib.rs
Implement a trait to convert an `AstarteDataEvent` into a rust struct. Since the implementation is repetitive and has to pass some standard checks, a derive macro is also implemented for named structs. It will parse the fields of the struct and extract the appropriate endpoints values from the event.
=> feat(derive):  implement the FromEvent trait and derive macro

CHANGELOG.md, src/transport/mqtt/mod.rs
This can lead to fewer allocations when we already have an owned variable.
=> refactor(mqtt): pass owned object to not clone internally

CHANGELOG.md, Cargo.lock, Cargo.toml, astarte-device-sdk-derive/CHANGELOG.md
All notable changes to this project will be documented in this file.
- Remove debug macro
- Bump Rust version to 1.72.0
- Pass owned object to not clone internally
=> Prepare release v0.7.1

Cargo.toml, astarte-device-sdk-derive/Cargo.toml
Update the includes and exclude in the Cargo manifest to add the `.sqlx/` directory. This fixes a bug in the cargo vendoring process that would exclude those files that are actually required to build the crate.
=> fix(cargo): update exclude and includes

CHANGELOG.md, examples/object_datastream/README.md, examples/registration/README.md, queries/delete_interface.sql, sqlx-data.json, src/interface/mod.rs, src/lib.rs, src/payload.rs, src/store/error.rs, src/store/memory.rs, src/store/mod.rs, src/store/sqlite.rs, src/store/wrapper.rs
Implement in the store a way to remove all the properties for an interface. This fixes the deletion of the properties when an interface is removed, since before it was using the mapping without the parameter.
Closes #312
=> fix(store): remove interface's properties

CHANGELOG.md, astarte-device-sdk-derive/src/lib.rs, e2e-test/src/main.rs, e2e-test/src/mock_data_datastream.rs, e2e-test/src/mock_data_property.rs, e2e-test/src/utils.rs, examples/individual_datastream/main.rs, examples/individual_properties/main.rs, src/aggregate.rs, src/event.rs, src/interface/mapping/path.rs, src/interface/mod.rs, src/interface/reference.rs, src/interfaces.rs, src/lib.rs, src/store/mod.rs, src/store/sqlite.rs, src/transport/grpc/convert.rs, src/transport/grpc/mod.rs, src/transport/mod.rs, src/transport/mqtt/mod.rs, src/transport/mqtt/payload.rs, src/types.rs, src/validate.rs
Move the Unset to the `Aggregation` enum and introduce a new `unset` method. This simplify the checks since you can only unset a property and the AstarteType::Unset is not needed in the others code paths. Also this simplifies the conversions in the gRPC code that now in infallible.
=> refactor(unset): remove the AstarteType::Unset

CHANGELOG.md, Cargo.lock, Cargo.toml, astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-derive/Cargo.lock, astarte-device-sdk-derive/Cargo.toml
- Delete all interface's properties, using the correct mapping, when an
interface is removed
=> chore: prepare release v0.6.5

Cargo.toml
We need to specify all files in the include directive.
=> fix(Cargo.toml): include and exclude

CHANGELOG.md, src/interfaces.rs, src/transport/grpc/mod.rs, src/transport/mqtt/mod.rs
There was a bug in the iteration that would iterate only on the single added interface in the method Interfaces::iter_with_added. This will generate an incorrect introspection for MQTT connection.
=> fix(interfaces): correct the iteration logic

.reuse/dep5, CHANGELOG.md, Cargo.lock, Cargo.toml, astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-mock/CHANGELOG.md
- Correct the interfaces iterator logic to send the correct device introspection [#334](https://github.com/astarte-platform/astarte-device-sdk-rust/pull/334)
=> chore(release): prepare release v0.8.1

Cargo.lock, Cargo.toml
This is necessary to avoid deps conflicts in the Message Hub
=> chore(deps): pin message hub proto version for dynamic introspection

Cargo.lock, Cargo.toml
Update the requirements for the version on the times, serde and sqlx crates.
=> fix(deps): pin to newer minimal-versions

.github/workflows/ci.yaml, .github/workflows/coverage.yaml, .github/workflows/test.yaml
Use the workflow_run to upload the coverage report, since it's run on base and has access to the repository secrets.
=> chore(coverage): upload to codecove from master

CHANGELOG.md, Cargo.lock, Cargo.toml, astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-mock/CHANGELOG.md
Bump version in Cargo.toml and update the CHANGELOG.md.
=> chore(release): prepare release v0.8.3

Cargo.toml, astarte-device-sdk-mock/src/lib.rs, examples/individual_datastream/main.rs, src/client.rs, src/connection.rs, src/prelude.rs, src/transport/mod.rs, src/transport/mqtt/client.rs, src/transport/mqtt/error.rs, src/transport/mqtt/mod.rs
Implement the `DisconnectClient` trait on the `DeviceClient`, because after the `handle_events` takes ownership of the connection. The client needs to send the disconnect over the connection and then the connection will handle it and both tasks will exit.
Depends on #363
=> feat(disconnect): move disconnect to the client

CHANGELOG.md, Cargo.lock, Cargo.toml, src/transport/grpc/mod.rs
Reflect the astarte-message-hub-proto changes: the node id information has been removed from the attach rpc parameter, which now contains only the introspection.
=> Use node id metedata in the attach rpc

astarte-device-sdk-mock/src/lib.rs, examples/individual_datastream/main.rs, src/client.rs, src/transport/grpc/mod.rs, src/transport/mod.rs, src/transport/mqtt/mod.rs
Make the disconnect usable with the gRPC connection, before the trait was implemented for the wrong struct and the error was not returned. Now the call to disconnect can fail but it only takes a reference, so you can retry it multiple times.
=> fix(disconnect): rework the disconnect for gRPC

astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-derive/src/event.rs, astarte-device-sdk-derive/src/lib.rs, src/event.rs, src/lib.rs, src/transport/mqtt/payload.rs, src/types.rs
Derive the FromEvent trait for interfaces with aggregation individual. This will  require the Rust item to be an `enum` with a variant for each of the mapping's endpoint. To distinguish the aggregation, a name-value pair was added to the `#[from_event]` attribute. All the derive macros have also been updated and changed to use the `attributes` instead of providing a different macro to pars them.
=> feat(derive): implement FromEvent for individual

CHANGELOG.md, Cargo.lock, Cargo.toml, astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-mock/CHANGELOG.md
Update the CHANGELOG and bump the version in the Cargo.toml
=> chore(release): prepare release v0.8.4

migrations/0002_unset_property.sql, queries/properties/read/interface_props.sql, queries/properties/read/load_all_props.sql, queries/properties/read/load_prop.sql, queries/properties/read/props_with_unset.sql, queries/properties/write/unset_prop.sql, src/connection.rs, src/store/error.rs, src/store/memory.rs, src/store/mod.rs, src/store/sqlite/mod.rs, src/store/sqlite/statements.rs, src/store/wrapper.rs, src/transport/mqtt/connection.rs, src/transport/mqtt/mod.rs
Do not send properties when we are offline, also unset the property
before sending it. This will let us, if offline, resend the unset when
re-connected and delete the property only if actually sent.
=> feat(prop): handle properties when offline 

astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-derive/src/event.rs, astarte-device-sdk-derive/src/lib.rs, src/event.rs
Add the attribute `allow_unset` to make the value of an individual property be wrapped in an `Option` when the value is un `Value::Unset`.
=> feat(derive): add allow unset for Optional values

.github/workflows/check.yaml
This tool checks the documentation with the same configuration and options as docs.rs.
=> chore(ci): use docs-rs for checking the doc

.github/workflows/check.yaml, CHANGELOG.md, Cargo.lock, Cargo.toml, astarte-device-sdk-mock/Cargo.toml, src/transport/mqtt/crypto.rs
Use `rcgen` from the `rustls` family of crates to generate the CSR for the pairing with Astarte. This let us remove 3 dependencies that broke the generation of the documentation.
=> refactor(crypto): move to rcgen for the csr

CHANGELOG.md, Cargo.lock, Cargo.toml, astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-mock/CHANGELOG.md
Bump versions in Cargo.toml and update the CHANGELOGs.
=> chore(release): prepare release v0.9.1

CHANGELOG.md, Cargo.lock, Cargo.toml, REUSE.toml, astarte-device-sdk-derive/CHANGELOG.md, astarte-device-sdk-mock/CHANGELOG.md
Bump version in Cargo.toml and update CHANGELOGs.
=> chore(release): prepare for release v0.9.3

src/interface/error.rs
The error why an interface couldn't be added was not showing the full
backtrace.
=> fix(error): add source macro to backtrace

Cargo.lock, Cargo.toml, src/transport/grpc/convert.rs, src/transport/grpc/mod.rs
Refactor of the grpc convert module to simplify the code and to support the updated proto definition.
BREAKING CHANGE: functions and trait implementations exposed by the grpc::convert trait changed
=> chore(grpc): Update message hub proto definitions

Cargo.lock
Upstream fixed a wrong CMake version that broke the windows build.
=> chore(deps): update aws-lc-rs to fix upstream bug

src/transport/grpc/mod.rs
Convert the status to a string an only return the code.
=> fix(clippy): warning on the size of the tonic::Status type

Cargo.lock, Cargo.toml, src/transport/grpc/convert.rs
requires [#74](https://github.com/astarte-platform/astarte-message-hub-proto/pull/74) to be merged first
=> Reflect proto changes after `AstarteDatastreamIndividual` typo fix 

rust-toolchain.toml
Before, we were using beta for an error with rust-analyzer and the new release was still not out. Now we can move to the stable channel, since the bug was fixed upstream.
=> chore(rust-toolchain): update to stable 1.86.0

e2e-test/src/main.rs, src/builder.rs, src/client.rs, src/connection.rs, src/error.rs, src/interfaces.rs, src/lib.rs, src/transport/grpc/mod.rs, src/transport/mod.rs, src/transport/mqtt/pairing.rs, src/transport/mqtt/payload.rs, src/validate.rs
Check the interface type, ownership and aggregation in the user
validation. Return an hard error if one is incorrect.
=> refactor!(validation): make it stricter to reflect the new API

Cargo.lock
See rust-lang/rust PR 139671 and dtolnay/proc-macro2 PR 497 for more information.
=> chore(proc-macro2): update to build with latest nightly

CHANGELOG.md, src/store/sqlite/mod.rs, src/store/sqlite/statements.rs
Allow setting the sqlite database size by providing either the maximum number of db pages or a size in KB, KiB, MB or MiB. Give also the possibility to set the journal size when building an `SQLiteStore`. Also set default pragma when connecting to an sqlite store.
Closes #450
=> feat(sqlite): set max db size

src/transport/mqtt/client.rs, src/transport/mqtt/retention.rs
This will make the select more responsive when a future is ready, before
it would take one more call to the poll function.
=> fix(mqtt): use a manual future to poll the retention tokens

CHANGELOG.md, Cargo.toml, src/builder.rs, src/connection/incoming.rs, src/lib.rs, src/retention/mod.rs, src/retention/sqlite/mod.rs, src/retention/sqlite/statements.rs, src/session/mod.rs, src/session/sqlite/mod.rs, src/session/sqlite/statement.rs, src/store/mod.rs, src/store/sqlite/connection.rs, src/store/sqlite/mod.rs, src/store/sqlite/options.rs, src/store/sqlite/pool.rs, src/store/sqlite/statements.rs, src/utils/const_conv.rs, src/utils/mod.rs
Do not use the thread locals for the sqlite connections, but a pool that will be dropped when the program exits.
If you test the e2e on the release-0.10 branch the following file will remain after it finishes:
```
prop-cache.db-shm
prop-cache.db-wal
```
On the current branch when the pool is dropped all the files are cleaned up.
=> refactor(sqlite): create a pool for the read connection
