examples/object.rs
src/interfaces.rs
src/lib.rs
src/types.rs

hashmap was bad so we use a struct

Refactor send object api

---

src/lib.rs

Signed-off-by: shikoku1 <87471904+shikoku1@users.noreply.github.com>

Add configurable keepalive

---

Cargo.toml
README.md
examples/database.rs
examples/datatypes.rs
examples/deviceproperties.rs
examples/interfaces/org.astarte-platform.genericsensors.AvailableSensors.json
examples/object.rs
examples/simple.rs
src/builder.rs
src/database.rs
src/interface.rs
src/interfaces.rs
src/lib.rs
src/pairing.rs
src/registration.rs
src/types.rs

changes:
- add sanity checks when receiving data
- database check before sending properties
- bugfix database for deceiving data
- documentation
- tests

Add Additional Checks, Bugfix, Documentation and Tests

---

Cargo.toml

This is useful for cargo-bitbake tool
Signed-off-by: Philippe Coval <philippe.coval@huawei.com>

build: Add repository URL

---

examples/database.rs
examples/deviceproperties.rs
src/builder.rs

Add license notice to missing files

Add license notice to missing files

---

examples/database.rs
examples/datatypes.rs
examples/deviceproperties.rs
examples/object.rs
examples/simple.rs
src/builder.rs
src/interfaces.rs
src/lib.rs
src/pairing.rs

Fixes the builder pattern for it to work in the correct way

Improve AstarteBuilder for better ergonomics

---

.github/dependabot.yml
.github/workflows/build-workflow.yaml
.github/workflows/reuse-lint.yaml
.gitignore
.reuse/dep5
Cargo.toml
LICENSES/Apache-2.0.txt
LICENSES/CC0-1.0.txt
README.md
examples/database.rs
examples/datatypes.rs
examples/deviceproperties.rs
examples/object.rs
examples/registration.rs
examples/simple.rs
src/builder.rs
src/crypto.rs
src/database.rs
src/interface.rs
src/interface/traits.rs
src/interfaces.rs
src/lib.rs
src/pairing.rs
src/registration.rs
src/types.rs

Make it compliant with https://reuse.software/
This change will improve license and copyright tracking, using SPDX and enforcing checks using CI.

Make it compliant with REUSE and add GH workflow

---

Cargo.toml
src/lib.rs

https://docs.astarte-platform.org/latest/080-mqtt-v1-protocol.html#purge-properties

Add purge properties logic

---

src/lib.rs

Move connack handling inside new(), to avoid a data race when sending data

Move connack handling inside new()

---

src/lib.rs

Derive clone for Aggregation and Clientbound

Derive Clone for Aggregation and Clientbound

---

src/lib.rs

- Fix the `device_session_not_found` error generated by reconnect, because the device not having all the [MQTT subscriptions required by the Astarte protocol](https://docs.astarte-platform.org/latest/080-mqtt-v1-protocol.html#mqtt-topics-overview).
- Remove the `cn` parameter from subscribe and use `self.client_id()` inside the function as all other functions that are building a topic

Move topics subscription in every connack

---

src/lib.rs

- Alter `add_interface` to get an Interface as parameter. 
- Add `add_interface_from_file` and `add_interface_from_str` to add a serialized interfaces to the introspection.

Add more ways to add interfaces to introspection

---

src/lib.rs

Fix (un)subscribe to server owned interface

---

.github/workflows/build-workflow.yaml
src/builder.rs
src/interface.rs
src/lib.rs
src/registration.rs

Adds support for clippy by fixing all its warnings and by adding clippy to the CI.
Closes #62.

Adds support for clippy

---

Cargo.toml
src/pairing.rs

Update rumqttc to v0.19

---

Cargo.toml
src/e2etest/e2etest.rs
src/registration.rs

Update base64 to v0.21

---

Cargo.toml

Update sqlx to v0.62

---

src/interfaces.rs

Fix unset property from server

---

src/e2etest/e2etest.rs
src/types.rs

Implement TryFrom for Vec<f64>

---

Cargo.toml
astarte-device-sdk-derive/Cargo.toml

Fix the documentation link in Cargo.toml

---

.reuse/dep5
CHANGELOG.md
Cargo.toml
astarte-device-sdk-derive/CHANGELOG.md
astarte-device-sdk-derive/Cargo.toml

Prepare 0.5.0 release

---

CHANGELOG.md
Cargo.toml

Lock version of flate2

---

src/pairing.rs
src/registration.rs

Use `reqwest::StatusCode` instead of `http::StatusCode`

---

.github/workflows/build-workflow.yaml
.github/workflows/e2e-test.yaml
.github/workflows/test-workflow.yaml
README.md

Add code coverage 

---

astarte-device-sdk-derive/Cargo.toml
astarte-device-sdk-derive/src/case.rs
astarte-device-sdk-derive/src/lib.rs
src/lib.rs

Adds attribute for struct renaming

---

.github/workflows/build-workflow.yaml
.github/workflows/test-workflow.yaml
.github/workflows/test.yaml
Cargo.lock
Cargo.toml

Update the MSRV to 1.66.1 in the Cargo.toml and CI files, and update dependencies.
Closes #189

 feat(msrv): update the MSRV 1.59.0 -> 1.66.1 

---

Cargo.lock

The lock file was out of date, and the build was failing because of it.

fix(lock): rebuild Cargo.lock

---

Cargo.lock
Cargo.toml
benches/benchmark.rs
src/crypto.rs

Make a benchmark to confront the different crypto libraries we have
for the certificate generation.

 test(crypto): add benchmark for the different crypto libraries 

---

CHANGELOG.md

We already do not feel confident to release this library as stable.

Revert version from 1.0.0 to 0.6.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
astarte-device-sdk-derive/CHANGELOG.md
astarte-device-sdk-derive/Cargo.lock
astarte-device-sdk-derive/Cargo.toml
src/error.rs

Forward port in master of the release 0.6.0

Forward port of release 0.6.0

---

CHANGELOG.md
README.md
examples/individual_datastream/main.rs
examples/individual_properties/main.rs
examples/object_datastream/main.rs
src/error.rs
src/lib.rs
src/payload.rs
src/retry.rs
src/shared.rs
src/store/error.rs
src/store/mod.rs
src/store/sqlite.rs
tests/e2etest/main.rs

Feat event loop

---

CHANGELOG.md
Cargo.lock
Cargo.toml
astarte-device-sdk-derive/CHANGELOG.md
astarte-device-sdk-derive/Cargo.lock
astarte-device-sdk-derive/Cargo.toml

Update Cargo.toml and CHANGELOG to release version v0.6.1

Prepare release v0.6.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
astarte-device-sdk-derive/CHANGELOG.md
astarte-device-sdk-derive/Cargo.lock
astarte-device-sdk-derive/Cargo.toml

Update Cargo.toml and CHANGELOG to release version v0.6.2

Prepare release v0.6.2

---

.github/workflows/test.yaml
.gitignore
CHANGELOG.md
Cargo.lock
Cargo.toml
src/builder.rs
src/error.rs
src/lib.rs
src/store/sqlite.rs
src/topic.rs
src/transport/grpc/convert.rs
src/transport/grpc/mod.rs
src/transport/mod.rs
src/transport/mqtt/mod.rs
src/transport/mqtt/payload.rs
src/types.rs
src/validate.rs

Implemented grpc transport and integrated message hub type conversions.

Grpc integration

---

.github/codecov.yaml
.github/workflows/check.yaml
.github/workflows/ci.yaml
.github/workflows/dco.yaml
.github/workflows/e2e-test.yaml
.github/workflows/reuse-lint.yaml
.github/workflows/test.yaml
README.md

Add sccache and use reusable workflow to have a single file entry-point.

ci: refactor to use reusable workflow and sccache

---

src/lib.rs
src/transport/grpc/mod.rs

Add clippy warn for dbg macros.

fix(dbg): remove debug macro

---

src/aggregate.rs
src/connection.rs
src/error.rs
src/event.rs
src/interface/def.rs
src/interface/error.rs
src/interface/mapping/endpoint.rs
src/interface/mapping/path.rs
src/interface/mod.rs
src/interface/reference.rs
src/introspection.rs
src/lib.rs
src/store/mod.rs
src/store/sqlite.rs
src/transport/grpc/mod.rs
src/transport/mod.rs
src/transport/mqtt/crypto.rs
src/transport/mqtt/error.rs
src/transport/mqtt/pairing.rs
src/types.rs

Add warning and documentation for missing doc comments on public items or modules.
Closes #257

feat(doc): add documentation to all public items

---

src/introspection.rs
src/transport/mqtt/mod.rs

fix(subscribe): check empty interfaces' list

---

CHANGELOG.md
astarte-device-sdk-mock/src/lib.rs
src/client.rs
src/connection.rs
src/introspection.rs

Improve the DynamicIntrospection by adding a return value letting us know if and which interfaces have been added or removed from or to the introspection.

feat(introspection): improve the api for checks

---

Cargo.lock
Cargo.toml

chore(deps): bump astarte message hub proto to 0.6.2

---

astarte-device-sdk-mock/Cargo.toml
astarte-device-sdk-mock/README.md

Add cargo description and readme to publish the crate.

fix(mock): add cargo description and readme

---

astarte-device-sdk-mock/src/lib.rs

Add the mock for the PropAccess trait on the client.

fix(mock): add impl for PropAccess trait

---

CHANGELOG.md
src/lib.rs

fix(purge): purge only server owned properties

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/transport/grpc/mod.rs

Use Empty type rather than Node to detach a Node

Refactor detach

---

CHANGELOG.md
src/transport/mqtt/config/mod.rs

Add the derive for Clone on the Credential and improve the Debug implementation showing the variant.

feat(mqtt): derive Clone for Credential

---

.github/workflows/check.yaml
.github/workflows/ci.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/interface/error.rs
src/transport/mqtt/config/tls.rs

Fixes an upstream bug in the MQTT unsubscribe.

chore(deps): update rumqttc dependency

---

CHANGELOG.md
Cargo.lock
Cargo.toml
astarte-device-sdk-derive/src/event.rs
src/introspection.rs
src/lib.rs
src/properties.rs
src/transport/mqtt/config/mod.rs
src/transport/mqtt/config/tls.rs
src/transport/mqtt/config/transport.rs
src/transport/mqtt/connection.rs
src/transport/mqtt/mod.rs
src/transport/mqtt/pairing.rs

Avoid using native certs when webpki feature is enabled
Closes #387

feat(webpki): use Mozilla webpki root certificates

---

Cargo.lock
Cargo.toml
src/transport/grpc/convert.rs
src/transport/grpc/mod.rs

Move timestamp from AstarteMessage to AstarteDatastreamIndividual/Object

refactor(timestamp): reflect proto timestamp changes

---

src/interfaces.rs

chore(interfaces): warn when an interface name ends in `.json`
